version: '3.9'

services:
  flask_ai:
    build:
      context: F:/SY_work/Sparta/Project/flask_ai  # Flask AI 프로젝트의 Dockerfile 위치
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    networks:
      - maiddy_shared_network  # Django 백엔드와 동일 네트워크 사용


networks:
  maiddy_shared_network:
    external: true  # 이미 백엔드 Docker Compose에서 정의된 네트워크 사용
