# version: '3.9'
services:
  maiddy_ai:
    build:
      context: .  # Flask AI 프로젝트의 Dockerfile 위치
    command: flask run --host=0.0.0.0 --port=5000
    container_name: maiddy_ai
    ports:
      - "5000:5000"
    networks:
      - maiddy_shared_network  # Django 백엔드와 동일 네트워크 사용

    environment: # .env 파일에 있는 환경변수를 사용.
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}


networks:
  maiddy_shared_network: # 백엔드 네트워크 이름.
    external: true  # 이미 백엔드 Docker Compose에서 정의된 네트워크 사용
